// Curated lucide icon re-exports. App code imports icons from here ONLY,
// so swapping the icon library later touches this one file.
export {
  // chrome / nav
  Menu,
  X,
  Search,
  Plus,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  PanelLeftClose,
  PanelLeftOpen,
  MoreHorizontal,
  MoreVertical,
  Settings,
  Info,
  ExternalLink,
  // queue / downloads
  Download,
  Pause,
  Play,
  Square,
  Trash2,
  FolderOpen,
  File as FileIcon,
  RefreshCw,
  Clock,
  // status / tone
  Check,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  Lock,
  Loader2,
  // media
  Film,
  Video,
  AudioLines,
  ListVideo,
  // misc
  Copy,
  Command,
  Keyboard,
  LayoutGrid,
  ScanLine,
  Filter,
  Globe,
  Activity,
  Github,
  Monitor,
  ListChecks,
} from 'lucide-react';
